version: '3.8'

services:
  react:
    image: node:18-alpine
    container_name: ford-app-dev
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"  # puerto que Vite usa por defecto
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
